[versions]
agp = "9.3.2"
xposed-api = "102.0.0"

[libraries]
xposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposed-api" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

